clc;
close all;
I=imread("cameraman.tif");
subplot(2,2,1);
imshow(I);
title("Original image");
g=edge(I,'canny');
subplot(2,2,2);
imshow(g);
title("Canny edge detector");
h=edge(I,'canny',[0.1,0.4]);
subplot(2,2,3);
imshow(h);
title("Canny threshold");
k=edge(I,'canny',[0.1,0.4],10);
subplot(2,2,4);
imshow(k);
title("C-T-S");
l=edge(I,'canny',[0.1,0.4],'horizontal');
subplot(2,2,5);
imshow(l);
title("C-T-D");
