clc;
close all;
I=imread("cameraman.tif");
SI=imnoise(I,"salt & pepper");
GI=imnoise(I,"gaussian");
ord=1;
Kr=3;
Kc=3;
Sg=im2double(SI);
SF=imfilter(Sg.^(ord+1),ones(Kr,Kc),'replicate')./(imfilter(Sg.^(ord),ones(Kr,Kc),'replicate')+eps);
Gg=im2double(GI);
GF=imfilter(Gg.^(ord+1),ones(Kr,Kc),'replicate')./(imfilter(Gg.^(ord),ones(Kr,Kc),'replicate')+eps);
subplot(2,2,1);
imshow(SI);
title("Salt and pepper noise");
subplot(2,2,2);
imshow(SF);
title("Filtered image");
subplot(2,2,3);
imshow(GI);
title("Gaussian noise");
subplot(2,2,4);
imshow(GF);
title("Filtered image");
