I=imread("cameraman.tif");
figure;
imshow(I);
title("Original image");
[cA,cH,cV,cD]=dwt2(I,'db4');
figure;
imshow(cV,[]);
title("Vertical Detail Coefficients");
figure;
imshow(cA,[]);
title("Approximation Coefficients");
figure;
imshow(cD,[]);
title("Diagonal Coefficients");
figure;
imshow(cH,[]);
title("Horizontal Coefficients");
Y=idwt2(cA,cH,cV,cD,'db4');
figure;
imshow(Y,[]);
title("Inverse Wavelet Transformed image");
