clc;
close all;
I=imread("cameraman.tif");
SI=imnoise(I,"salt & pepper");
GI=imnoise(I,"gaussian");
Kr=3;
Kc=3;
Sg=im2double(SI);
SF=exp(imfilter(log(Sg),ones(Kr,Kc),"replicate")).^(1/(Kr*Kc));
Gg=im2double(GI);
GF=exp(imfilter(log(Gg),ones(Kr,Kc),"replicate")).^(1/(Kr*Kc));
subplot(2,2,1);
imshow(SI);
title("Salt and pepper noise");
subplot(2,2,2);
imshow(SF);
title("Filtered image");
subplot(2,2,3);
imshow(GI);
title("Gaussian noise");
subplot(2,2,4);
imshow(GF);
title("Filtered image");
