clc;
close all;
I=imread("cameraman.tif");
SI=imnoise(I,"salt & pepper");
GI=imnoise(I,"gaussian");
Kr=3;
Kc=3;
Sg=im2double(SI);
SF=(Kr*Kc)./(imfilter(1./(Sg+eps),ones(Kr,Kc),"replicate"));
Gg=im2double(GI);
GF=(Kr*Kc)./(imfilter(1./(Gg+eps),ones(Kr,Kc),"replicate"));
subplot(2,2,1);
imshow(SI);
title("Salt and pepper noise");
subplot(2,2,2);
imshow(SF);
title("Filtered Image");
subplot(2,2,3);
imshow(GI);
title("Gaussian noise");
subplot(2,2,4);
imshow(GF);
title("Filtered Image");
