clc;
close all;
I=imread("cameraman.tif");
ft=fftshift(fft2(I));
[m,n ]=size(ft);
norm_img=@(img)(img-min(img(:)))/(max(img(:))-min(img(:)));
show_spec=@(img)imshow(norm_img(log(abs(img)-min(abs(img(:)))+1.0001)));
gNotch = @(v,mu,cov)1-exp(-0.5*sum((bsxfun(@minus,v,mu).*(cov\bsxfun(@minus,v,mu)))));
subplot(2,2,1);
show_spec(ft);
cx=129;
cy=129;
wx1=149.5-129;
wx2=165.5-129;
wy=157.5-129;
filt=ones(m,n);
sigma=5;
[y,x ]=meshgrid(1:n,1:m);
X=[ y(:) x(:)].';
filt=filt.*reshape(gNotch(X,[cx+wx1;cy+wy],eye(2)*sigma^2),[m,n]);
filt=filt.*reshape(gNotch(X,[cx+wx2;cy+wy],eye(2)*sigma^2),[m,n]);
filt=filt.*reshape(gNotch(X,[cx-wx1;cy-wy],eye(2)*sigma^2),[m,n]);
filt=filt.*reshape(gNotch(X,[cx-wx2;cy-wy],eye(2)*sigma^2),[m,n]);
ft=ft.*filt;
subplot(2,2,2);
show_spec(ft);
ifft_=ifft2(ifftshift(ft));
img_res=histeq(norm_img(ifft_));
subplot(2,2,3);
imshow(img_res);
