clc;
close all;
x=imread("cameraman.tif");
figure,imshow(x);title("original image");
fcol=fftshift(fft(x,[],1));
fcol=log(1+abs(fcol));
frow=fftshift(fft(fcol,[],2));
frow=log(1+abs(frow));
fall=fftshift(fft2(x));
fall=log(1+abs(fall));
figure;
subplot(121);
imshow(fcol,[]);
title("row transform");
subplot(122);
imshow(frow,[]);
title("column transform");
figure;
imshow(fall,[]);
title("2D transform");
