clc;
close all;
a=imread("cameraman.tif");
subplot(2,2,1);
imshow(a);
title("Original image");
a=im2double(a);
PSF = fspecial("motion",21,11);
a_blurred = imfilter(a,PSF,"conv","circular");
noise_mean=0;
noise_var=0.0001;
signal_var=var(a(:));
NSR=noise_var/signal_var;
a_blurred=imnoise(a_blurred,"gaussian",noise_mean,noise_var);
subplot(2,2,2);
imshow(a_blurred);
title("Blurred image");
DD=deconvwnr(a_blurred,PSF,NSR);
subplot(2,2,3);
imshow(DD);
title("Restored image");
